# Generated by Django 4.0.1 on 2022-01-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_war_vidio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(auto_created=True, unique=True)),
                ('date', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=64)),
                ('describtion', models.TextField()),
                ('start', models.DateTimeField()),
                ('registaration_finish', models.DateTimeField()),
                ('price', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
